### PR TITLE
remove the alert for a better smooth navigation on the web

### PR DESCRIPTION
**Pull request by YalpLeYak**

### CODE REVIEW

**Review by AnastasiosTsio — CHANGES_REQUESTED** [review]
Useless comment

**Review by noahkohrs — CHANGES_REQUESTED** [review]
Dumb PR.
Please remove the comment

**Review by noahkohrs — APPROVED** [review]
GJJJJ

**Review by AnastasiosTsio — COMMENTED** [review]
Could you add a success message in another way maybe letting know the user that the captcha is passed?

**Comment by YalpLeYak** [comment]
anastasios go back to work

**Review by AnastasiosTsio — APPROVED** [review]
Good job.

**Pull request merged**
